SELECT EmployeeNumber, FirstName, LastName
FROM EMPLOYEE
WHERE EmployeeNumber NOT IN
 (SELECT DISTINCT EmployeeNumber
 FROM ASSIGNMENT)
ORDER BY EmployeeNumber


SELECT DISTINCT EmployeeNumber
FROM EMPLOYEE
WHERE NOT EXISTS (
SELECT *
FROM ASSIGNMENT
WHERE NOT EXISTS (
SELECT *
FROM DEPARTMENT
ORDER BY EmployeeNumbeer
)
);
