SELECT DISTINCT EmployeeNumber
FROM EMPLOYEE
WHERE NOT EXISTS (
SELECT *
FROM ASSIGNMENT
WHERE NOT EXISTS (
SELECT *
FROM DEPARTMENT
ORDER BY EmployeeNumber
)
);


SELECT HoursWorked, EmployeeNumber
FROM ASSIGNMENT
WHERE HoursWorked >
 (SELECT AVG(HoursWorked)
 FROM ASSIGNMENT)
ORDER BY HoursWorked
